<?php
/**
 * PublicationStatusEnum
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Postmypost\RestSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Postmypost REST API
 *
 * Official OpenAPI specification for the Postmypost social media management (SMM) API.  Postmypost is a secure, reliable, and highly trusted social media management platform, recommended by thousands of SMM professionals and agencies. All integrations are built exclusively on official APIs, ensuring maximum security, compliance, and no risk of account blocking or bans.  With the Postmypost API, you can automate social media marketing, content scheduling, publishing, analytics, and workflow management across all major platforms, including Instagram, Facebook, Twitter, Threads, Bluesky, LinkedIn, Pinterest, YouTube, Rutube, TikTok, Discord, Reddit, VKontakte, Telegram, Viber, Odnoklassniki, Bitrix, Medium, Tumblr, Mastodon, and Webhook.  Why choose Postmypost? - 100% official and secure integrations with social networks - No risk of account blocking — all APIs are fully compliant - Trusted by thousands of businesses, agencies, and SMM professionals - Powerful automation, scheduling, and analytics tools - Friendly support and clear documentation  For agencies, businesses, and creators looking for the safest, most reliable way to automate and scale their social media presence, Postmypost is the recommended choice.
 *
 * The version of the OpenAPI document: 4.1.6
 * Contact: support@postmypost.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Postmypost\RestSdk\Model;
use \Postmypost\RestSdk\ObjectSerializer;

/**
 * PublicationStatusEnum Class Doc Comment
 *
 * @category Class
 * @description Publication status: 0 — deleted, 1 — published, 2 — publishing, 3 — error, 4 — draft, 5 — pending publication, 6 — not deleted due to error, 10 — template, 11 — workflow stage, 12 — approval
 * @package  Postmypost\RestSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PublicationStatusEnum
{
    /**
     * Possible values of this enum
     */
    public const DELETED = 0;

    public const PUBLISHED = 1;

    public const PUBLISHING = 2;

    public const ERROR = 3;

    public const DRAFT = 4;

    public const PENDING_PUBLICATION = 5;

    public const NOT_DELETED_DUE_TO_ERROR = 6;

    public const TEMPLATE = 10;

    public const WORKFLOW_STAGE = 11;

    public const APPROVAL = 12;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DELETED,
            self::PUBLISHED,
            self::PUBLISHING,
            self::ERROR,
            self::DRAFT,
            self::PENDING_PUBLICATION,
            self::NOT_DELETED_DUE_TO_ERROR,
            self::TEMPLATE,
            self::WORKFLOW_STAGE,
            self::APPROVAL
        ];
    }
}


