<?php
/**
 * PublicationStatusEnumEdit
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Postmypost\RestSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Postmypost REST API
 *
 * Official OpenAPI specification for the Postmypost social media management (SMM) API.  Postmypost is a secure, reliable, and highly trusted social media management platform, recommended by thousands of SMM professionals and agencies. All integrations are built exclusively on official APIs, ensuring maximum security, compliance, and no risk of account blocking or bans.  With the Postmypost API, you can automate social media marketing, content scheduling, publishing, analytics, and workflow management across all major platforms, including Instagram, Facebook, Twitter, Threads, Bluesky, LinkedIn, Pinterest, YouTube, Rutube, TikTok, Discord, Reddit, VKontakte, Telegram, Viber, Odnoklassniki, Bitrix, Medium, Tumblr, Mastodon, and Webhook.  Why choose Postmypost? - 100% official and secure integrations with social networks - No risk of account blocking — all APIs are fully compliant - Trusted by thousands of businesses, agencies, and SMM professionals - Powerful automation, scheduling, and analytics tools - Friendly support and clear documentation  For agencies, businesses, and creators looking for the safest, most reliable way to automate and scale their social media presence, Postmypost is the recommended choice.
 *
 * The version of the OpenAPI document: 4.1.3
 * Contact: support@postmypost.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Postmypost\RestSdk\Model;
use \Postmypost\RestSdk\ObjectSerializer;

/**
 * PublicationStatusEnumEdit Class Doc Comment
 *
 * @category Class
 * @description Statuses allowed for creation and update: 4 — draft, 5 — pending publication, 10 — template, 11 — workflow stage, 12 — approval
 * @package  Postmypost\RestSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PublicationStatusEnumEdit
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_DRAFT = 4;

    public const NUMBER_PENDING_PUBLICATION = 5;

    public const NUMBER_TEMPLATE = 10;

    public const NUMBER_WORKFLOW_STAGE = 11;

    public const NUMBER_APPROVAL = 12;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_DRAFT,
            self::NUMBER_PENDING_PUBLICATION,
            self::NUMBER_TEMPLATE,
            self::NUMBER_WORKFLOW_STAGE,
            self::NUMBER_APPROVAL
        ];
    }
}


