<?php
/**
 * UploadStatusEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Postmypost\RestSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Postmypost REST API
 *
 * Official OpenAPI specification for the Postmypost social media management (SMM) API.  Postmypost is a secure, reliable, and highly trusted social media management platform, recommended by thousands of SMM professionals and agencies. All integrations are built exclusively on official APIs, ensuring maximum security, compliance, and no risk of account blocking or bans.  With the Postmypost API, you can automate social media marketing, content scheduling, publishing, analytics, and workflow management across all major platforms, including Instagram, Facebook, Twitter, Threads, Bluesky, LinkedIn, Pinterest, YouTube, Rutube, TikTok, Discord, Reddit, VKontakte, Telegram, Viber, Odnoklassniki, Bitrix, Medium, Tumblr, Mastodon, and Webhook.  Why choose Postmypost? - 100% official and secure integrations with social networks - No risk of account blocking — all APIs are fully compliant - Trusted by thousands of businesses, agencies, and SMM professionals - Powerful automation, scheduling, and analytics tools - Friendly support and clear documentation  For agencies, businesses, and creators looking for the safest, most reliable way to automate and scale their social media presence, Postmypost is the recommended choice.
 *
 * The version of the OpenAPI document: 4.1.4
 * Contact: support@postmypost.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Postmypost\RestSdk\Model;
use \Postmypost\RestSdk\ObjectSerializer;

/**
 * UploadStatusEnum Class Doc Comment
 *
 * @category Class
 * @description Upload status: 5 — waiting for upload, 4 — uploading, 3 — processing, 2 — error, 1 — file uploaded successfully
 * @package  Postmypost\RestSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UploadStatusEnum
{
    /**
     * Possible values of this enum
     */
    public const NUMBER_FILE_UPLOADED_SUCCESSFULLY = 1;

    public const NUMBER_ERROR = 2;

    public const NUMBER_PROCESSING = 3;

    public const NUMBER_UPLOADING = 4;

    public const NUMBER_WAITING_FOR_UPLOAD = 5;

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NUMBER_FILE_UPLOADED_SUCCESSFULLY,
            self::NUMBER_ERROR,
            self::NUMBER_PROCESSING,
            self::NUMBER_UPLOADING,
            self::NUMBER_WAITING_FOR_UPLOAD
        ];
    }
}


